### ISSUE TITLE
Proposal: Add tricknotes as maintainer

### ISSUE THREAD

**Issue by josh** [babel/ruby-babel-transpiler#118]
@tricknotes thanks for being so much help so far. Curious if you're interested in being added as a maintainer? Basically repo access and gem publish access.

Just trying to remove me as the bus number for this gem. No worries if your not interested.

**Comment by tricknotes** [comment]
Thanks for mention, @josh .
I'm interested in it.

I'll run with your ball :smile:

**Comment by josh** [comment]
Done. Thanks!!!!

**Comment by tricknotes** [comment]
Confirmed, thanks ;)
