### ISSUE TITLE
Community publishing creds

### ISSUE THREAD

**Issue by josh** [babel/ruby-babel-transpiler#128]
Hey guys,

I'm wondering if theres any conventions around shared babel community maintainer credentials. I have a few things registered under my api tokens and would like to know if we could move those under a shared account and keep the creds in a safe spot so @josh isn't a single point of failure here.

* [x] Need a rubygems.org account/token to publish to babel-transpiler and babel-source
* [ ] A free heroku account to run the webhook instance https://github.com/babel/ruby-babel-transpiler/tree/heroku
* [ ] A babelbot github account to automatically open PRs from

/cc @tricknotes @sebmck @thejameskyle

**Comment by thejameskyle** [comment]
We could setup an email for it. I started to setup a google apps for babeljs.io, I didn't realize they started charging for that.

**Comment by josh** [comment]
Got the rubygems stuff setup.

Might just punt on the webhook + bot thing for now.
