### ISSUE TITLE
babel-source lagging latest release

### ISSUE THREAD

**Issue by sethcall** [babel/ruby-babel-transpiler#268]
There are multiple pull requests from tricknotes outstanding; is it possible to update to the latest babel-source (5.8.22?)

In particular, async/await has moved to stage 2 (it's why I bother to ask).

**Comment by tricknotes** [comment]
Right.
But these PRs are failed to build. Such as https://travis-ci.org/babel/ruby-babel-transpiler/jobs/75009673 

To publish for new release, it should be fixed.
If you are interest in this fix, you can try it.

**Comment by sethcall** [comment]
Alright thanks.

Well, I tried first to just run this command locally:

./script/test-gem 5.8.22

And I had no failure (on MacOSX).   I'm looking around now at what's different between my environment and Travis.

**Comment by sethcall** [comment]
This is where the script fails: 

babel/scripts/build-dist.sh

This change is probably the source of the issue:
https://github.com/babel/babel/commit/beaff831d2c4b6c499581c6587e73999a5c18494#diff-729e8ddea0774d4b82a61a79615d6a9e

That change helped solve this  issue:
https://github.com/babel/babel/issues/340

So I sort of know the problem; no idea as to the fix.

**Comment by sethcall** [comment]
I'm trying to recreate the build-dist issue on Linux.

**Comment by sethcall** [comment]
Ok, it's a build-dist.sh issue on Linux. I've created an issue there: 

https://github.com/babel/babel/issues/2255

**Comment by tricknotes** [comment]
Thanks for your probe!

**Comment by sethcall** [comment]
Well, they merged my fix into master, but there isn't a new version yet, so you can't get a build out with the way your build scripts work until that happens.  I'll close this bug with the assumption the next release will get put out there!

Thanks!
Seth

**Comment by tricknotes** [comment]
Awesome thanks @sethcall !
The [babel-source@5.8.23](https://rubygems.org/gems/babel-source/versions/5.8.23) is released via https://github.com/babel/ruby-babel-transpiler/pull/269 .

**Comment by sethcall** [comment]
Awesome!   Thanks @tricknotes
