### ISSUE TITLE
ExecJS doesn't allow printing error messages from Babel

### ISSUE THREAD

**Issue by ralekna** [babel/ruby-babel-transpiler#284]
I have a huge legacy JavaScript file and I decided to start converting it into ES6 module. 

When I compile it using babel-cli I get such warning:
`Note: The code generator has deoptimised the styling of "myscript.js" as it exceeds the max of "100KB".`

But when I try to compile it by using this gem, internally used ExecJS can't display that message because it doesn't have such thing as `console` and is not planing to have one (https://github.com/sstephenson/execjs/issues/91 and https://github.com/sstephenson/execjs/blob/master/test/test_execjs.rb#L237).

Current solution while still using ExecJS would be to define dummy `console` object with its dummy functions like `log` and `error` but then all such errors like this will be eaten by void.

**Comment by tricknotes** [comment]
This is the expected ExecJS's behavior.
