### ISSUE TITLE
Research Travis deploy hook for publishing gems

### ISSUE THREAD

**Issue by josh** [babel/ruby-babel-transpiler#62]
Travis has support to automatically publishing gems after a successful build. I think something like this could work for mirroring the source gems. But the weird thing here is that somehow a build for ruby-6to5 would need to be triggered when a 6to5 tag was created. I'm wondering if theres some hacky way to setup another webhook on 6to5 proper to trigger ruby-6to5 builds.

* http://docs.travis-ci.com/user/deployment/rubygems/
* http://docs.travis-ci.com/user/deployment/custom/

/cc @sebmck @thejameskyle

**Comment by sebmck** [comment]
I'm happy to add whatever hooks necessary.

**Comment by josh** [comment]
Seems like the limitation is that theres no way to trigger a manual build for travis. It always needs a commit that would be in ruby-6to5 itself. And you couldn't pass along whatever 6to5 version was just released.

**Comment by sebmck** [comment]
I'd be fine with adding `ruby-6to5` as a git submodule and adding `$ rake source_gem[VERSION]` to my `$ make publish` process if there's no other way.

**Comment by josh** [comment]
@sebmck thats nice of you to offer, but I think it would end up giving you trouble you shouldn't have to deal with.

**Comment by josh** [comment]
Making some progress on an interesting approach.

Right now to release new source version, you have to add a new entry to this "source-versions.txt" file https://github.com/6to5/ruby-6to5/blob/master/source-versions.txt.

That change can be committed and pushed and CI will actually attempt to build the new versions and run tests on them before its actually released. Then theres a second `./script/publish` step that I've been running manually to push out any unpublished ones. I think that last part could be automated on Travis.

So heres the workflow I'm trying to get to. Some kind of web hook automatically opens new PRs against ruby-6to5 adding a new version to `source-versions.txt`. Travis can actually build and verify that the new version is going to work. Then I can just click merge and Travis will auto release it.

A few nice things about this. We'll never auto release a broken gem. Sometimes the format changes in 6to5 source and the script needs to be updated. A failed build will indicate this. Now anyone with commit access to this repo can technically release new versions by merging PRs.

**Comment by josh** [comment]
Alright, got a webhook server up on heroku.

@sebmck could you add a webhook for me on https://github.com/babel/babel that pings https://ruby-babel-transpiler-7688.herokuapp.com/ for all new tag creations.

![screen shot 2015-02-22 at 2 15 11 pm](https://cloud.githubusercontent.com/assets/137/6320194/5f4403b6-ba9d-11e4-9e22-8e1a0e69e0ae.png)

**Comment by thejameskyle** [comment]
Added.

**Comment by josh** [comment]
Success!

Started documenting the release process here https://github.com/babel/ruby-babel-transpiler/blob/master/SOURCE-BUILDS.md
