### ISSUE TITLE
Rename gem

### ISSUE THREAD

**Issue by josh** [babel/ruby-babel-transpiler#88]
The current gem is named `6to5` and unfortunately `babel` is already a registered gem.

* [x] Confirm name
* [x] Rename repository
* [ ] Publish new gem
* [x] Publish new source gems

/cc @sebmck

**Comment by sebmck** [comment]
> unfortunately `babel` is already a registered gem.

Shit... can't say I'm surprised though. Any ideas?

**Comment by josh** [comment]
I think it should be `babel-`something. Like `babel-transpiler`, `babel-transformer`, `babelify`... Have any of the other plugins hit this collision? If so what'd they go with.

**Comment by sebmck** [comment]
They didn't fortunately. "babel" was previously used by a dead translation library on npm and the GitHub username was occupied by an inactive/dead user so everything related to it was free.

**Comment by sebmck** [comment]
`babelify` is used by the browserify plugin so that's probably not a good idea. `babel-transpiler` sounds good.

**Comment by josh** [comment]
Aight, done.
